[package]
name = "entanglement_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
akton = { git = "ssh://git@github.com/GovCraft/akton-framework.git", akton = "quasar", branch = "main" }
