name: ChangeLog generation
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: "ubuntu-latest"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
          repository: "Govcraft/ntangler"
          token: "${{ secrets.PAT }}"

      - name: Install gitchglog
        run: |
          wget https://github.com/git-chglog/git-chglog/releases/download/v0.15.4/git-chglog_0.15.4_linux_amd64.tar.gz
          tar -xvzf git-chglog_0.15.4_linux_amd64.tar.gz

      - name: Generate changelog
        run: ./git-chglog -o CHANGELOG.md

      - name: Check-in updated CHANGELOG
        uses: EndBug/add-and-commit@v9
        with:
          add: './CHANGELOG.md'
          author: 'rrrodzilla'
          author_email: 'rrrodzilla@proton.me'
          message: 'chore(release): update CHANGELOG'
